from torchmetrics.functional.text.resources.function_words import arabic  # noqa: F401
from torchmetrics.functional.text.resources.function_words import czech  # noqa: F401
from torchmetrics.functional.text.resources.function_words import danish  # noqa: F401
from torchmetrics.functional.text.resources.function_words import dutch  # noqa: F401
from torchmetrics.functional.text.resources.function_words import english  # noqa: F401
from torchmetrics.functional.text.resources.function_words import finnish  # noqa: F401
from torchmetrics.functional.text.resources.function_words import french  # noqa: F401
from torchmetrics.functional.text.resources.function_words import german  # noqa: F401
from torchmetrics.functional.text.resources.function_words import hungarian  # noqa: F401
from torchmetrics.functional.text.resources.function_words import italian  # noqa: F401
from torchmetrics.functional.text.resources.function_words import norwegian  # noqa: F401
from torchmetrics.functional.text.resources.function_words import other  # noqa: F401
from torchmetrics.functional.text.resources.function_words import portuguese  # noqa: F401
from torchmetrics.functional.text.resources.function_words import romanian  # noqa: F401
from torchmetrics.functional.text.resources.function_words import russian  # noqa: F401
from torchmetrics.functional.text.resources.function_words import spanish  # noqa: F401
from torchmetrics.functional.text.resources.function_words import swedish  # noqa: F401
from torchmetrics.functional.text.resources.function_words import turkish  # noqa: F401
