trigger:
  tags:
    include:
      - "*"
# run every month to sanitatize dev environment
schedules:
  - cron: "0 0 1 * *"
    displayName: Monthly nuke caches
    branches:
      include:
        - master
# run on PR changing only this file
pr:
  branches:
    include:
      - master
  paths:
    include:
      - .azure/gpu-nuke-cache.yml

jobs:
  - job: nuke_caches
    # how long to run the job before automatically cancelling
    timeoutInMinutes: "10"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"

    pool: "lit-rtx-3090"

    variables:
      # these two caches assume to run repetitively on the same set of machines
      #  see: https://github.com/microsoft/azure-pipelines-agent/issues/4113#issuecomment-1439241481
      TORCH_HOME: "/var/tmp/torch"
      TRANSFORMERS_CACHE: "/var/tmp/hf/transformers"
      HF_HOME: "/var/tmp/hf/home"
      HF_HUB_CACHE: "/var/tmp/hf/hub"
      PIP_CACHE_DIR: "/var/tmp/pip"
      CACHED_REFERENCES: "/var/tmp/cached-references.zip"

    container:
      image: "ubuntu:22.04"
      options: "-v /var/tmp:/var/tmp"

    steps:
      - bash: |
          set -ex
          rm -rf $(TORCH_HOME)
          rm -rf $(TRANSFORMERS_CACHE)
          rm -rf $(HF_HOME)
          rm -rf $(HF_HUB_CACHE)
          rm -rf $(PIP_CACHE_DIR)
          rm -rf $(CACHED_REFERENCES)
        displayName: "delete all caches"
      - bash: |
          ls -lh /var/tmp
        displayName: "show tmp/ folder"
