name: Update caches & artifacts
description: some more complex push-caches - pip & hf

inputs:
  cache-torch-HF:
    description: "cache torch and HF"
    required: false
    default: "true"
  cache-references:
    description: "cache metrics references"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Show Torch & HF
      if: inputs.cache-torch-HF == 'true' # since the input is string
      run: py-tree $CACHES_DIR
      shell: bash

    - name: Cache Torch & HF
      if: inputs.cache-torch-HF == 'true' # since the input is string
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        enableCrossOsArchive: true
        path: ${{ env.CACHES_DIR }}
        key: ci-caches

    - name: Cache references
      if: inputs.cache-references == 'true' # since the input is string
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        #enableCrossOsArchive: true
        path: tests/_cache-references
        key: cache-references

    #- name: Post References
    #  # This print taken soo many lines, so it is commented out
    #  if: inputs.cache-references == 'true' # since the input is string
    #  run: py-tree tests/_cache-references/ --show_hidden
    #  shell: bash
