name: Greetings
# https://github.com/marketplace/actions/first-interaction

on: [issues] # pull_request

jobs:
  greeting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: "Hi! Thanks for your contribution! Great first issue!"
          pr_message: "Hey thanks for the input! Please give us a bit of time to review it!"
